### ISSUE TITLE
I purchased platinum plan for 12 month for auto forward bot from app but still I didn't get my plan😭

### ISSUE THREAD

**Issue by ishanvenghat** [redf0x1/Auto-Forward-Messages#4]
I purchased auto forward bot platinum plan for 12 month from the app that you gave.but still my plan is free.help me to give me my platinum account or recover my money.i can't contact you in telegram for sending proof because of the privacy setting that says you can only send message to mutual contacts.my user id 1360492823.my telegram username @ishaanvenghat

**Comment by redf0x1** [comment]
Please contact to my telegram @redf0x1 and send me your order id for check

**Comment by redf0x1** [comment]
Anyone can message me unless you are suspected of being scammed by telegram and you are not allowed to message anyone. Or you can use any telegram account to send me an invoice

**Comment by ishanvenghat** [comment]
I can't because of your privacy settings

**Comment by redf0x1** [comment]
Why u not send your order id here???
